{% set name = "dbt-semantic-interfaces" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dbt_semantic_interfaces-{{ version }}.tar.gz
  sha256: 4afecc6dc56f85ecce7ac424dea07561513467e0bf28ead7307b78a22e6b999b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - pydantic >=1.10,<2.dev0
    - jsonschema >=3.0,<4.dev0
    - pyyaml >=6.0,<7.dev0
    - more-itertools >=8.0,<9.dev0
    - jinja2 >=3.0,<4.dev0
    - click >=7.0,<9.0
    - python-dateutil >=2.0,<3.dev0
    - importlib-metadata >=6.0,<7.dev0
    - typing-extensions >=4.0,<5.dev0

test:
  imports:
    - dbt_semantic_interfaces
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dbt-labs/dbt-semantic-interfaces
  summary: The shared semantic layer definitions that dbt-core and MetricFlow use
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jthandy
    - maresb
