{% set name = "dbt-semantic-interfaces" %}
{% set version = "0.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dbt_semantic_interfaces-{{ version }}.tar.gz
  sha256: e0f03461250725f0472644cf412fe5893fa669f768e4abf4a62121753f558724

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - typing_extensions >=4.4,<5
    - python >=3.8
    - pydantic >=1.10,<3
    - jsonschema >=4.0,<5
    - pyyaml >=6.0,<7
    - more-itertools >=8.0,<11.0
    - jinja2 >=3.1.3,<4
    - click >=7.0,<9.0
    - python-dateutil >=2.0,<3
    - importlib-metadata <7,>=6.0
    - typing-extensions >=4.4,<5

test:
  imports:
    - dbt_semantic_interfaces
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dbt-labs/dbt-semantic-interfaces
  summary: The shared semantic layer definitions that dbt-core and MetricFlow use
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
    - maresb
