{% set name = "dbt-semantic-interfaces" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dbt_semantic_interfaces-{{ version }}.tar.gz
  sha256: 6d6e890abad147e46ebbf4a1c505607c855010dd4e5701111beeb5ca3b3b5df4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - typing_extensions >=4.4,<5
    - pydantic >=1.10,<3
    - jsonschema >=4.0,<5
    - pyyaml >=6.0,<7
    - more-itertools >=8.0,<11.0
    - jinja2 >=3.1.6,<4
    - click >=7.0,<8.3
    - python-dateutil >=2.0,<3
    - importlib-metadata <9,>=6.0
    - typing-extensions >=4.4,<5

test:
  imports:
    - dbt_semantic_interfaces
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/dbt-labs/dbt-semantic-interfaces
  summary: The shared semantic layer definitions that dbt-core and MetricFlow use
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
    - maresb
