{% set name = "dbt-semantic-interfaces" %}
{% set version = "0.8.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dbt_semantic_interfaces-{{ version }}.tar.gz
  sha256: b01e5533a9fdc9503865d3610ccee36b6f7b5c14f9950f628607d3eff10ad466

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - typing_extensions >=4.4,<5
    - pydantic >=1.10,<3
    - jsonschema >=4.0,<5
    - pyyaml >=6.0,<7
    - more-itertools >=8.0,<11.0
    - jinja2 >=3.1.6,<4
    - click >=7.0,<9.0
    - python-dateutil >=2.0,<3
    - importlib-metadata <9,>=6.0
    - typing-extensions >=4.4,<5

test:
  imports:
    - dbt_semantic_interfaces
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/dbt-labs/dbt-semantic-interfaces
  summary: The shared semantic layer definitions that dbt-core and MetricFlow use
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
    - maresb
